name: leapfrog-py test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   py: '3.13'}
          - {os: ubuntu-latest,  py: '3.10'}
          - {os: ubuntu-latest,  py: '3.11'}
          - {os: ubuntu-latest,  py: '3.12'}
          - {os: ubuntu-latest,  py: '3.13'}
          - {os: windows-latest, py: '3.13'}

    name: ${{matrix.config.os }} (${{ matrix.config.py }})
    runs-on: ${{ matrix.config.os }}

    defaults:
      run:
        working-directory: leapfrog-py

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "leapfrog-py/uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.config.py }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true
          extra-repositories: https://mrc-ide.r-universe.dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::here
          needs: check
          working-directory: leapfrogr

      - name: Create test data
        working-directory: leapfrogr
        shell: bash
        run: ./scripts/create_test_data.R

      - name: Run tests
        run: uv run pytest

      - name: Lint
        run: uvx ruff check .

      - name: Test install
        run: |
          pip install .
          python -c "import leapfrog_py"
